// import type { Metadata } from "next";
// import "./globals.css";
// import { Button } from "@/components/ui/button";
// import Navbar from "@/components/ui/navbar";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
     
//       <body
//         className= ""
//       >
//         <div>
        
//           {children}
//           <Navbar />

//         </div>
//       </body>
//     </html>
//   );
// }


// src/app/layout.tsx
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import Navbar from "@/components/ui/navbar";
import SessionProvider from "@/utils/SessionProvider";
// import Footer from "./footer/page";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div className="mx-auto  text-2xl gap-2 mb-10  ">
            <Navbar />
            {children}
          </div>
          <Toaster richColors closeButton position="top-right"/>
          {/* <Footer/> */}
        </SessionProvider>
        
      </body>
    </html>
  );
}
